<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class productTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //make 10 products with data
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21',
            'product_slug' => 'samsung-galaxy-s21',
            'product_code' => 'S21',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/01.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 Ultra',
            'product_slug' => 'samsung-galaxy-s21-ultra',
            'product_code' => 'S21U',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/02.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 Plus',
            'product_slug' => 'samsung-galaxy-s21-plus',
            'product_code' => 'S21P',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/03.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 FE',
            'product_slug' => 'samsung-galaxy-s21-fe',
            'product_code' => 'S21FE',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/04.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/05.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/06.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/07.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 20),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/08.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/09.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/10.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/11.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/12.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
        DB::table('products')->insert([
            'brand_id' => rand(1, 5),
            'category_id' => rand(1, 10),
            'subcategory_id' => rand(1, 100),
            'product_name' => 'Samsung Galaxy S21 5G',
            'product_slug' => 'samsung-galaxy-s21-5g',
            'product_code' => 'S215G',
            'product_qty' => rand(1, 150),
            'product_tags' => 'samsung, s21, galaxy',
            'product_size' => 'S, M, L, XL',
            'product_color' => 'Black, White, Blue, Red',
            'selling_price' => 1000,
            'discount_price' => 900,
            'short_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.short',
            'long_descp' => 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quisquam, quod.long',
            'product_thambnail' => 'upload/products/thambnail/13.png',
            'vendor_id' => 2,
            'hot_deals' => rand(0, 1),
            'featured' => rand(0, 1),
            'special_offer' => rand(0, 1),
            'special_deals' => rand(0, 1),
            'status' => 1,
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }
}
